### ISSUE TITLE
Cannot bulid a sloop

### ISSUE THREAD

**Issue by OliviaSiIence** [HyperDashPony/FirmaCiv#61]
When building a sloop, the two scaffoldings at the bow cannot be correctly identified. Even after placing the copper bolts and cleats, the correct structure cannot be formed.

**Comment by thombongaards** [comment]
I have the same issue. The scaffolding behaves like stairs, yet the constructing the mod wants you to make is just not possible with the way stairs (and therefore scaffolding) behave.

Also, the orientation of the cleats (the last step) also seems to be influence by the rotation of the stairs, which is anoying as it also prevents the cleats from being placed correctly. Meaning that the cleat placement probably also needs fixing.

**Comment by HyperDashPony** [comment]
It's possible to build sloops. The instructions are pretty clear and the scaffolding placement is absolutely possible. It might be re-done in the future since people can't figure it out. Cleats will be placed on the side of the block closest to you, which means you should place them from outside of the hull.

**Comment by thombongaards** [comment]
Ah so that is what I was doing wrong. The fact that the patchouli visualise thingy wasn't recognizing the scaffolding was throwing me off. Placing the cleats from outside the hull is what I was doing wrong, that wasn't quite clear. My mistake! Thank you for clarifying!
